### ISSUE TITLE
Users are able to easily access Swagger with no need to setup an environment

### ISSUE THREAD

**Issue by giovaroma** [masa-finance/masa-oracle#451]
Problem statement: Users are not able to quickly get up and running and make API calls. By using AWS and setting up an environment with the protocol we will be able to expose swagger where users will be able to immediately make API calls across channels. 

Acceptance criteria:

- [x] Set up AWS environment with the required protocol setup
- [x] Expose Swagger UI through the AWS environment
- [ ] Test API calls for each channel through Swagger

**Comment by mudler** [comment]
plannings outcome:

- The API will be available at api-playground.masa.ai

**Comment by 5u6r054** [comment]
This is partially ready. Now, if you go here: https://test.api.masa.ai/ you will be redirected here: https://test.api.masa.ai/swagger/index.html -- but the requests don't work due to issues with the configuration within the masa-oracle code.

This setup is done with an ALB, route53, and the subdomain test.api.masa.ai is delegated from cloudflare to the AWS account (masa-opentensor-test). The same will work for the main and dev accounts for dev.api.masa.ai (though we're not really using this account) and main.api.masa.ai when we get there.

The miners-config.json has a new field that can be set on one miner group, "api_server": true.  If set, the alb will use miners in that group as targets. The ALB terminates SSL and redirects requests to the root to swagger/index.html

However, it's ugly to see swagger/index.html in the URL bar. 

Next step is a PR to masa-oracle codebase to server swagger/index.html at the root instead. 

Also, the requests do not work because the base URL is set to http://localhost:8080/ -- this must be changed to be relative. 

Will create PR to masa-oracle repo to fix these aspects next.

**Comment by 5u6r054** [comment]
btw the infra component of this is here: 

https://github.com/masa-finance/masa-oracle-infra/tree/test/aws/opentensor

primarily in the alb.tf and route53.tf files.
